#对空格要求十分严格，尤其注意空格缩进
server:
  port: 8080
  servlet:
    #web路径
    context-path: /du
#选择启动模块
spring:
  profiles:
    active: test

#可以用debug查看哪些自动装配成功那些未成功
#debug: true
---
server:
  port: 8081
spring:
  profiles: dev
  thymeleaf:
    cache: false
    messages:
      basename: i18n.login
---
server:
  port: 8082
spring:
  profiles: test
  #关闭模板引擎缓存
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
#Ymal 可以写对象
cat:
  name: qiutian
  age: 3
#行内写法
cat2: {name: qiutian,age: 3}

#数组
pets:
  - cat
  - dog
  - pig

pets2: [cat,dog,pig]

# 可把值注入到配置文件中
person:
  name: dyd@123.com
  age: 6
  happy: true
  birth: 1995/4/7
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - nagirl
  dog:
    name: 夏天
    age:  1

